set termencoding=utf-8
set encoding=utf-8
set fileencodings=iso-2022-jp,euc-jp,cp932,sjis,utf-8
set fileformats=unix,dos,mac
set backspace=indent,eol,start
set number
set tabstop=2
set autoindent
set expandtab
set shiftwidth=2
set foldcolumn=2
set foldmethod=indent
